spring.application.name=hmsexperience
# management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=HMS Experience API
info.app.description="API to be consumed by front-end application."
info.app.version=1.0

spring.security.user.name=admin
spring.security.user.password=password